SHOW_FRAMES = True

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

#IMAGE PROCESSING
IMAGE_HEIGHT = 64
IMAGE_WIDTH = 256
IMAGE_CHANNELS = 3

TRAINING_DIRECTORY = 'C:\\Users\\Adam\\Documents\\NN\\AITruckingProject\\Data'